[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "geodepot"
version = "2024.1001"
authors = [
    {name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl"},
]
description = ""
readme = "README.md"
requires-python = ">=3.11"
keywords = []
license = {text = "Apache-2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "gdal",
    "pdal",
    "pyproj",
    "click",
    "requests"
]

[project.optional-dependencies]
dev = ["pytest", "pyinstaller", "black", "isort", "mkdocs", "mkdocs-material"]

[project.scripts]
geodepot = "geodepot:cli.geodepot_grp"

[tool.isort]
profile = "black"
