[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "geodepot"
version = "1.0.0"
authors = [
    {name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl"},
]
description = "Test data storage system for geospatial data"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["geospatial", "software-testing"]
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "gdal==3.9.1",
    "pdal==2.7.2",
    "pyproj==3.6.1",
    "click==8.1.7",
    "requests==2.32.3"
]

[project.optional-dependencies]
dev = ["pytest", "pyinstaller", "briefcase", "ruff", "bumpver", "mkdocs", "mkdocs-material"]

[project.scripts]
geodepot = "geodepot:cli.geodepot_grp"

[tool.ruff]
src = ["src", "tests"]

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
