name: Install, Lint, Format, Test

on:
  push:
    branches: ["main"]

jobs:
  all:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - if: runner.os == 'Windows'
        name: Install wget on Windows
        run: choco install wget

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          manifest-path: pyproject.toml
          environments: dev
          activate-environment: dev
          locked: true
          cache: true

      - name: Download test data
        run: pixi run -e dev download-data

      - name: Test if GDAL imports
        run: python -c "import osgeo"

      - name: Lint
        run: pixi run -e dev lint

      - name: Format
        run: pixi run -e dev format-check

      - name: Run unit tests
        run: pixi run -e dev test
